ref #75993 Refactor RetailcrmProxy API
retailcrm/prestashop-module pull request #138
Opened 2021-08-17 07:20 UTC by Apcenuu

2021-08-30 07:18 UTC, root-aza commented on retailcrm/lib/interfaces/RetailcrmProxyMiddlewareInterface.php
> +    public function process(RetailcrmApiRequest $request, RetailcrmApiResponse $response);
В чем проблема передавать 3 аргументом следующую миддлваре?

2021-08-30 07:18 UTC, root-aza commented on retailcrm/lib/RetailcrmLogger.php
> +    public static function reduceErrors($errors)
А это можно завернуть в отдельный форматтер

2021-08-30 07:18 UTC, root-aza commented on retailcrm/lib/api/RetailcrmApiRequest.php
> +    protected $api;
wtf

2021-08-30 07:18 UTC, root-aza commented on retailcrm/lib/api/RetailcrmApiRequest.php
> +    protected $api;
И где типы

2021-09-22 15:39 UTC, max-baranikov requested changes

2021-09-22 15:39 UTC, max-baranikov commented on retailcrm/lib/abstract/RetailcrmAbstractProxyMiddleware.php
> +    public function __invoke(RetailcrmApiRequest $request, RetailcrmApiResponse $response)
middleware в обрабботчике должна принимать $request и $next
RetailcrmApiResponse $response является возвращаемым значением

2021-09-22 15:39 UTC, max-baranikov commented on retailcrm/lib/api/RetailcrmProxy.php
> +        return $response;
Получается что сначала происходит action - вызов апи, а затем его запрос и ответ проходят по всем мидлварям. Это не является пайплайном в его обычном понимании, т.к. в такой ситуации не возможно модифицировать запрос и сделать какие-либо операции до отправления запроса.

Запрос ($request) сначала должен пройти все мидлвари, затем выполнится в экшене, после чего результат выполнения ($response), проходя опять же через все мидлвари возвращается в прокси

2021-09-22 15:39 UTC, max-baranikov commented on retailcrm/lib/builder/RetailcrmProxyBuilder.php
> +    public function run(RetailcrmApiRequest $request, RetailcrmApiResponse $response)
run должен принимать объект запроса ($request) и callback функцию действия - action
RetailcrmApiResponse $response является возвращаемым значением

2021-09-22 15:39 UTC, max-baranikov commented on retailcrm/lib/builder/RetailcrmProxyBuilder.php
> +        }
здесь нужен не поочередный запуск, а сформированный стек вызовов с вложенными друг в друга middleware, где каждая middleware вызывает следующую и так по цепочке до самого action-а

2021-09-22 15:39 UTC, max-baranikov commented on retailcrm/lib/middleware/RetailcrmLoggerMiddleware.php
> +        }
видимо из-за архитектурных решений на других уровнях здесь не реализована логика обработки (логирования)  сначала запроса, отправки его следующим мидлварям и последующей обработки (логирования) ответа
это также нужно доработать

2021-09-24 09:28 UTC, max-baranikov requested changes
пару доработок по неймингу и структуре:
* в аргументах вместо `Closure` лучше использовать `callable` как тип
* следует убрать префикс `Proxy` из `RetailcrmProxyMiddlewareInterface`, т.к. интерфейс в данной ситуации является общим и относится только к `RetailcrmPipeline`
* все, что связано с pipeline нужно перенести в одну папку` lib/pipeline`, в т.ч. интерфейсы и абстрактные классы
* папку `middleware` нужно переместить в `lib/api`, т.к. эта логика относится только к прокси

2021-09-24 09:28 UTC, max-baranikov commented on retailcrm/lib/builder/RetailcrmPipeline.php
> +    public $middlewares;
Массив мидлварей задавать в отдельно fluent-setter методе, поле сделать приватным

2021-09-24 09:28 UTC, max-baranikov commented on retailcrm/lib/builder/RetailcrmPipeline.php
> +    public function run(RetailcrmApiRequest $request, callable $action)
$action для конкретного пайплайна будет всегда один, потому его тоже можно вынести в отдельный fluent-setter
это позволит разделить сборку пайплайна от его запуска

2021-09-24 09:28 UTC, max-baranikov commented on retailcrm/lib/builder/RetailcrmPipeline.php
> +            );
Этот код нужно вынести в отдельный метод, например build()
Таким образом pipeline будет собираться один раз, и много раз запускаться. Сейчас он собирается заново при каждом вызове прокси

2021-09-24 09:28 UTC, max-baranikov commented on retailcrm/lib/builder/RetailcrmPipeline.php
> +    private function addMiddleware()
мб стоит как-нибудь переименовать метод, чтобы имя лучше отражало его суть

2021-09-28 10:29 UTC, closed without merging